name: Deploy to Pantheon

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: false

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  push-to-pantheon:
    permissions:
      deployments: write
      contents: read
      pull-requests: read  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Push to Pantheon
      # running again to test the removal of "unshallow"
      uses: stevector/push-to-pantheon@remove-force-pushing
      with:
        ssh_key: ${{ secrets.PANTHEON_SSH_KEY }}
        machine_token: ${{ secrets.TERMINUS_MACHINE_TOKEN }}
        site: algore-website
        # only bother to delete old environments when running on main branch
        delete_old_environments: ${{ github.ref == 'refs/heads/main' }}
