name: Deploy PR to Pantheon

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: false

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Pantheon
      uses: stevector-streaming/dtp/github_actions/deploy_single_site@stripping-bt7
      with:
        pantheon_ssh_key: ${{ secrets.PANTHEON_SSH_KEY }}
        terminus_machine_token: ${{ secrets.TERMINUS_MACHINE_TOKEN }}
        pantheon_site: algore-website
        target_env: "pr-${{ github.event.pull_request.number }}"
