name: Deploy main branch to Pantheon
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Pantheon
      uses: stevector-streaming/dtp@0.1.0
      with:
        pantheon_ssh_key: ${{ secrets.PANTHEON_SSH_KEY }}
        terminus_machine_token: ${{ secrets.TERMINUS_MACHINE_TOKEN }}
        pantheon_site: algore-website
        target_env: dev
        delete_old_environments: true
