name: Deploy to Pantheon

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: false

on:
  pull_request:
    types: [opened, edited, synchronize]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Pantheon
      uses: stevector-streaming/dtp@0.2.0
      
      with:
        pantheon_ssh_key: ${{ secrets.PANTHEON_SSH_KEY }}
        # todo, convert to pantheon_machine_token
        # https://github.com/stevector-streaming/dtp/pull/48
        terminus_machine_token: ${{ secrets.TERMINUS_MACHINE_TOKEN }}
        pantheon_site: algore-website
        # only bother to delete old environments when running on main branch
        delete_old_environments: ${{ github.ref == 'refs/heads/main' }}
