name: Deploy to Pantheon

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: false

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:

  
  first-terminus-auth:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Terminus
      uses: pantheon-systems/terminus-github-actions@v1
      with:
        pantheon-machine-token: ${{ secrets.TERMINUS_MACHINE_TOKEN }}

  
  repeated-terminus:
    needs: first-terminus-auth
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Terminus
      uses: pantheon-systems/terminus-github-actions@v1
      with:
        pantheon-machine-token: ${{ secrets.TERMINUS_MACHINE_TOKEN }}
