name: Deploy to Pantheon

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: false

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:

  
  first-terminus-auth:
    runs-on: ubuntu-latest
    steps:
    - name: Install Terminus
      uses: pantheon-systems/terminus-github-actions@v1
      with:
        pantheon-machine-token: ${{ secrets.TERMINUS_MACHINE_TOKEN }}
#        disable-cache: true

  
  repeated-terminus:
    strategy:
      matrix:
        a: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        b: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    needs: first-terminus-auth
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ matrix.a }} 
    - run: echo ${{ matrix.b }}
    - name: Install Terminus
      uses: pantheon-systems/terminus-github-actions@v1
      with:
        pantheon-machine-token: ${{ secrets.TERMINUS_MACHINE_TOKEN }}
 #       disable-cache: true
